name: test

on:
  push:
    branches:
      - master
    paths:
    - '**.go'
    - '.github/workflows/test.yml'
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"
      - name: Test
        run: go test -v ./... -coverprofile cover.out

      - name: Convert coverage to lcov
        uses: jandelgado/gcov2lcov-action@v1.0.9
        if: github.ref == 'refs/heads/master'
        with:
          infile: cover.out
          outfile: cover.lcov

      - name: Coveralls
        uses: coverallsapp/github-action@master
        if: github.ref == 'refs/heads/master'
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: cover.lcov
