name: test

on:
  push:
    paths:
    - '**.go'
    - '.github/workflows/test.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: go test -v -race ./...
